[package]
name = "mevboost-relay-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
mevboost-relay-api = { path = "../../crates/mevboost-relay-api" }
clap.workspace = true
anyhow.workspace = true
inquire.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true

csv = "1.3.0"
# url = "2.2.2"
# beacon-api-client = { git = "https://github.com/ralexstokes/ethereum-consensus.git" }
