[package]
name = "mevboost-relay-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
mevboost-relay-api = { path = "../../crates/mevboost-relay-api" }
clap.workspace = true
anyhow.workspace = true
inquire.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
